/* Generated by scripts/gen-catalog.mjs (pnpm catalog:build). */
import {VStack} from '@astryxdesign/core/Stack';
import React from 'react';

import PostArchiveShowcase from '../../_showcases/PostArchiveShowcase';
import {ComponentNav} from '../../_ui/ComponentNav';
import {ShowcaseBlock} from '../../_ui/ShowcaseBlock';

export const metadata = {title: 'Post Archive — Design system Vidomia'};

export default function Page() {
  return (
    <VStack gap={8}>
      <ShowcaseBlock name="PostArchive" id="post-archive" doc={null} dressed category="Mise en page">
        <PostArchiveShowcase />
      </ShowcaseBlock>
      <ComponentNav category="mise-en-page" current="post-archive" />
    </VStack>
  );
}
