/* Generated by scripts/gen-catalog.mjs (pnpm catalog:build). */
import {VStack} from '@astryxdesign/core/Stack';
import React from 'react';

import CollectionShowcase from '../../_showcases/CollectionShowcase';
import {ComponentNav} from '../../_ui/ComponentNav';
import {ShowcaseBlock} from '../../_ui/ShowcaseBlock';

export const metadata = {title: 'Collection — Design system Vidomia'};

export default function Page() {
  return (
    <VStack gap={8}>
      <ShowcaseBlock name="Collection" id="collection" doc={null} dressed category="Conteneurs">
        <CollectionShowcase />
      </ShowcaseBlock>
      <ComponentNav category="conteneurs" current="collection" />
    </VStack>
  );
}
