/* Generated by scripts/gen-catalog.mjs (pnpm catalog:build). */
import {VStack} from '@astryxdesign/core/Stack';
import React from 'react';

import KeyPointsShowcase from '../../_showcases/KeyPointsShowcase';
import {ComponentNav} from '../../_ui/ComponentNav';
import {ShowcaseBlock} from '../../_ui/ShowcaseBlock';

export const metadata = {title: 'Key Points — Design system Vidomia'};

export default function Page() {
  return (
    <VStack gap={8}>
      <ShowcaseBlock name="KeyPoints" id="key-points" doc={null} dressed category="Contenu">
        <KeyPointsShowcase />
      </ShowcaseBlock>
      <ComponentNav category="contenu" current="key-points" />
    </VStack>
  );
}
