/* Generated by scripts/gen-catalog.mjs (pnpm catalog:build). */
import {VStack} from '@astryxdesign/core/Stack';
import React from 'react';

import CaseHeroShowcase from '../../_showcases/CaseHeroShowcase';
import {ComponentNav} from '../../_ui/ComponentNav';
import {ShowcaseBlock} from '../../_ui/ShowcaseBlock';

export const metadata = {title: 'Case Hero — Design system Vidomia'};

export default function Page() {
  return (
    <VStack gap={8}>
      <ShowcaseBlock name="CaseHero" id="case-hero" doc={null} dressed category="Mise en page">
        <CaseHeroShowcase />
      </ShowcaseBlock>
      <ComponentNav category="mise-en-page" current="case-hero" />
    </VStack>
  );
}
