/* Generated by scripts/gen-catalog.mjs (pnpm catalog:build). */
import {VStack} from '@astryxdesign/core/Stack';
import React from 'react';

import CaseSheetShowcase from '../../_showcases/CaseSheetShowcase';
import {ComponentNav} from '../../_ui/ComponentNav';
import {ShowcaseBlock} from '../../_ui/ShowcaseBlock';

export const metadata = {title: 'Case Sheet — Design system Vidomia'};

export default function Page() {
  return (
    <VStack gap={8}>
      <ShowcaseBlock name="CaseSheet" id="case-sheet" doc={null} dressed category="Mise en page">
        <CaseSheetShowcase />
      </ShowcaseBlock>
      <ComponentNav category="mise-en-page" current="case-sheet" />
    </VStack>
  );
}
