/* Generated by scripts/gen-catalog.mjs (pnpm catalog:build). */
import {VStack} from '@astryxdesign/core/Stack';
import React from 'react';

import CtaBandShowcase from '../../_showcases/CtaBandShowcase';
import {ComponentNav} from '../../_ui/ComponentNav';
import {ShowcaseBlock} from '../../_ui/ShowcaseBlock';

export const metadata = {title: 'Cta Band — Design system Vidomia'};

export default function Page() {
  return (
    <VStack gap={8}>
      <ShowcaseBlock name="CtaBand" id="cta-band" doc={null} dressed category="Contenu">
        <CtaBandShowcase />
      </ShowcaseBlock>
      <ComponentNav category="contenu" current="cta-band" />
    </VStack>
  );
}
