/* Generated by scripts/gen-catalog.mjs (pnpm catalog:build). */
import {VStack} from '@astryxdesign/core/Stack';
import React from 'react';

import TabsShowcase from '../../_showcases/TabsShowcase';
import {ComponentNav} from '../../_ui/ComponentNav';
import {ShowcaseBlock} from '../../_ui/ShowcaseBlock';

export const metadata = {title: 'Tabs — Design system Vidomia'};

export default function Page() {
  return (
    <VStack gap={8}>
      <ShowcaseBlock name="Tabs" id="tabs" doc={null} dressed category="Conteneurs">
        <TabsShowcase />
      </ShowcaseBlock>
      <ComponentNav category="conteneurs" current="tabs" />
    </VStack>
  );
}
