/* Generated by scripts/gen-catalog.mjs (pnpm catalog:build). */
import {VStack} from '@astryxdesign/core/Stack';
import React from 'react';

import RichTextShowcase from '../../_showcases/RichTextShowcase';
import {ComponentNav} from '../../_ui/ComponentNav';
import {ShowcaseBlock} from '../../_ui/ShowcaseBlock';

export const metadata = {title: 'Rich Text — Design system Vidomia'};

export default function Page() {
  return (
    <VStack gap={8}>
      <ShowcaseBlock name="RichText" id="rich-text" doc={null} dressed category="Contenu">
        <RichTextShowcase />
      </ShowcaseBlock>
      <ComponentNav category="contenu" current="rich-text" />
    </VStack>
  );
}
