/* Generated by scripts/gen-catalog.mjs (pnpm catalog:build). */
import {VStack} from '@astryxdesign/core/Stack';
import React from 'react';

import PostTocShowcase from '../../_showcases/PostTocShowcase';
import {ComponentNav} from '../../_ui/ComponentNav';
import {ShowcaseBlock} from '../../_ui/ShowcaseBlock';

export const metadata = {title: 'Post Toc — Design system Vidomia'};

export default function Page() {
  return (
    <VStack gap={8}>
      <ShowcaseBlock name="PostToc" id="post-toc" doc={null} dressed category="Mise en page">
        <PostTocShowcase />
      </ShowcaseBlock>
      <ComponentNav category="mise-en-page" current="post-toc" />
    </VStack>
  );
}
