/* Generated by scripts/gen-catalog.mjs (pnpm catalog:build). */
import {VStack} from '@astryxdesign/core/Stack';
import React from 'react';

import PostHeaderShowcase from '../../_showcases/PostHeaderShowcase';
import {ComponentNav} from '../../_ui/ComponentNav';
import {ShowcaseBlock} from '../../_ui/ShowcaseBlock';

export const metadata = {title: 'Post Header — Design system Vidomia'};

export default function Page() {
  return (
    <VStack gap={8}>
      <ShowcaseBlock name="PostHeader" id="post-header" doc={null} dressed category="Mise en page">
        <PostHeaderShowcase />
      </ShowcaseBlock>
      <ComponentNav category="mise-en-page" current="post-header" />
    </VStack>
  );
}
