/* Generated by scripts/gen-catalog.mjs (pnpm catalog:build). */
import {VStack} from '@astryxdesign/core/Stack';
import React from 'react';

import StatsBandShowcase from '../../_showcases/StatsBandShowcase';
import {ComponentNav} from '../../_ui/ComponentNav';
import {ShowcaseBlock} from '../../_ui/ShowcaseBlock';

export const metadata = {title: 'Stats Band — Design system Vidomia'};

export default function Page() {
  return (
    <VStack gap={8}>
      <ShowcaseBlock name="StatsBand" id="stats-band" doc={null} dressed category="Contenu">
        <StatsBandShowcase />
      </ShowcaseBlock>
      <ComponentNav category="contenu" current="stats-band" />
    </VStack>
  );
}
