/* Generated by scripts/gen-catalog.mjs (pnpm catalog:build). */
import {VStack} from '@astryxdesign/core/Stack';
import React from 'react';

import EntryFaqShowcase from '../../_showcases/EntryFaqShowcase';
import {ComponentNav} from '../../_ui/ComponentNav';
import {ShowcaseBlock} from '../../_ui/ShowcaseBlock';

export const metadata = {title: 'Entry Faq — Design system Vidomia'};

export default function Page() {
  return (
    <VStack gap={8}>
      <ShowcaseBlock name="EntryFaq" id="entry-faq" doc={null} dressed category="Mise en page">
        <EntryFaqShowcase />
      </ShowcaseBlock>
      <ComponentNav category="mise-en-page" current="entry-faq" />
    </VStack>
  );
}
