/* Generated by scripts/gen-catalog.mjs (pnpm catalog:build). */
import {VStack} from '@astryxdesign/core/Stack';
import React from 'react';

import PostLayoutShowcase from '../../_showcases/PostLayoutShowcase';
import {ComponentNav} from '../../_ui/ComponentNav';
import {ShowcaseBlock} from '../../_ui/ShowcaseBlock';

export const metadata = {title: 'Post Layout — Design system Vidomia'};

export default function Page() {
  return (
    <VStack gap={8}>
      <ShowcaseBlock name="PostLayout" id="post-layout" doc={null} dressed category="Mise en page">
        <PostLayoutShowcase />
      </ShowcaseBlock>
      <ComponentNav category="mise-en-page" current="post-layout" />
    </VStack>
  );
}
