/* Generated by scripts/gen-catalog.mjs (pnpm catalog:build). */
import {VStack} from '@astryxdesign/core/Stack';
import React from 'react';

import RelatedPostsShowcase from '../../_showcases/RelatedPostsShowcase';
import {ComponentNav} from '../../_ui/ComponentNav';
import {ShowcaseBlock} from '../../_ui/ShowcaseBlock';

export const metadata = {title: 'Related Posts — Design system Vidomia'};

export default function Page() {
  return (
    <VStack gap={8}>
      <ShowcaseBlock name="RelatedPosts" id="related-posts" doc={null} dressed category="Mise en page">
        <RelatedPostsShowcase />
      </ShowcaseBlock>
      <ComponentNav category="mise-en-page" current="related-posts" />
    </VStack>
  );
}
