/* Generated by scripts/gen-catalog.mjs (pnpm catalog:build). */
import {VStack} from '@astryxdesign/core/Stack';
import React from 'react';

import SiteFormShowcase from '../../_showcases/SiteFormShowcase';
import {ComponentNav} from '../../_ui/ComponentNav';
import {ShowcaseBlock} from '../../_ui/ShowcaseBlock';

export const metadata = {title: 'Site Form — Design system Vidomia'};

export default function Page() {
  return (
    <VStack gap={8}>
      <ShowcaseBlock name="SiteForm" id="site-form" doc={null} dressed category="Formulaires">
        <SiteFormShowcase />
      </ShowcaseBlock>
      <ComponentNav category="formulaires" current="site-form" />
    </VStack>
  );
}
