/* Generated by scripts/gen-catalog.mjs (pnpm catalog:build). */
import {VStack} from '@astryxdesign/core/Stack';
import React from 'react';

import TextBoxShowcase from '../../_showcases/TextBoxShowcase';
import {ComponentNav} from '../../_ui/ComponentNav';
import {ShowcaseBlock} from '../../_ui/ShowcaseBlock';

export const metadata = {title: 'Text Box — Design system Vidomia'};

export default function Page() {
  return (
    <VStack gap={8}>
      <ShowcaseBlock name="TextBox" id="text-box" doc={null} dressed category="Contenu">
        <TextBoxShowcase />
      </ShowcaseBlock>
      <ComponentNav category="contenu" current="text-box" />
    </VStack>
  );
}
