import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-sqlite'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.run(sql`ALTER TABLE \`pages_blocks_card_image\` ADD \`tag\` text DEFAULT 'h3';`)
  await db.run(sql`ALTER TABLE \`pages_blocks_card_icon\` ADD \`tag\` text DEFAULT 'h3';`)
  await db.run(sql`ALTER TABLE \`pages_blocks_card_number\` ADD \`tag\` text DEFAULT 'h3';`)
  await db.run(sql`ALTER TABLE \`pages_blocks_card_title\` ADD \`tag\` text DEFAULT 'h3';`)
  await db.run(sql`ALTER TABLE \`pages_blocks_card_image_link\` ADD \`tag\` text DEFAULT 'h3';`)
  await db.run(sql`ALTER TABLE \`pages_blocks_card_icon_link\` ADD \`tag\` text DEFAULT 'h3';`)
  await db.run(sql`ALTER TABLE \`pages_blocks_card_number_link\` ADD \`tag\` text DEFAULT 'h3';`)
  await db.run(sql`ALTER TABLE \`pages_blocks_card_title_link\` ADD \`tag\` text DEFAULT 'h3';`)
  await db.run(sql`ALTER TABLE \`pages_blocks_price_single\` ADD \`guarantee_title_tag\` text DEFAULT 'p';`)
  await db.run(sql`ALTER TABLE \`pages_blocks_plan\` ADD \`name_tag\` text DEFAULT 'p';`)
  await db.run(sql`ALTER TABLE \`pages_blocks_plan\` ADD \`guarantee_title_tag\` text DEFAULT 'p';`)
  await db.run(sql`ALTER TABLE \`pages_blocks_process_steps\` ADD \`tag\` text DEFAULT 'h3';`)
  await db.run(sql`ALTER TABLE \`sections_blocks_card_image\` ADD \`tag\` text DEFAULT 'h3';`)
  await db.run(sql`ALTER TABLE \`sections_blocks_card_icon\` ADD \`tag\` text DEFAULT 'h3';`)
  await db.run(sql`ALTER TABLE \`sections_blocks_card_number\` ADD \`tag\` text DEFAULT 'h3';`)
  await db.run(sql`ALTER TABLE \`sections_blocks_card_title\` ADD \`tag\` text DEFAULT 'h3';`)
  await db.run(sql`ALTER TABLE \`sections_blocks_card_image_link\` ADD \`tag\` text DEFAULT 'h3';`)
  await db.run(sql`ALTER TABLE \`sections_blocks_card_icon_link\` ADD \`tag\` text DEFAULT 'h3';`)
  await db.run(sql`ALTER TABLE \`sections_blocks_card_number_link\` ADD \`tag\` text DEFAULT 'h3';`)
  await db.run(sql`ALTER TABLE \`sections_blocks_card_title_link\` ADD \`tag\` text DEFAULT 'h3';`)
  await db.run(sql`ALTER TABLE \`sections_blocks_price_single\` ADD \`guarantee_title_tag\` text DEFAULT 'p';`)
  await db.run(sql`ALTER TABLE \`sections_blocks_plan\` ADD \`name_tag\` text DEFAULT 'p';`)
  await db.run(sql`ALTER TABLE \`sections_blocks_plan\` ADD \`guarantee_title_tag\` text DEFAULT 'p';`)
  await db.run(sql`ALTER TABLE \`sections_blocks_process_steps\` ADD \`tag\` text DEFAULT 'h3';`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.run(sql`ALTER TABLE \`pages_blocks_card_image\` DROP COLUMN \`tag\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_card_icon\` DROP COLUMN \`tag\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_card_number\` DROP COLUMN \`tag\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_card_title\` DROP COLUMN \`tag\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_card_image_link\` DROP COLUMN \`tag\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_card_icon_link\` DROP COLUMN \`tag\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_card_number_link\` DROP COLUMN \`tag\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_card_title_link\` DROP COLUMN \`tag\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_price_single\` DROP COLUMN \`guarantee_title_tag\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_plan\` DROP COLUMN \`name_tag\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_plan\` DROP COLUMN \`guarantee_title_tag\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_process_steps\` DROP COLUMN \`tag\`;`)
  await db.run(sql`ALTER TABLE \`sections_blocks_card_image\` DROP COLUMN \`tag\`;`)
  await db.run(sql`ALTER TABLE \`sections_blocks_card_icon\` DROP COLUMN \`tag\`;`)
  await db.run(sql`ALTER TABLE \`sections_blocks_card_number\` DROP COLUMN \`tag\`;`)
  await db.run(sql`ALTER TABLE \`sections_blocks_card_title\` DROP COLUMN \`tag\`;`)
  await db.run(sql`ALTER TABLE \`sections_blocks_card_image_link\` DROP COLUMN \`tag\`;`)
  await db.run(sql`ALTER TABLE \`sections_blocks_card_icon_link\` DROP COLUMN \`tag\`;`)
  await db.run(sql`ALTER TABLE \`sections_blocks_card_number_link\` DROP COLUMN \`tag\`;`)
  await db.run(sql`ALTER TABLE \`sections_blocks_card_title_link\` DROP COLUMN \`tag\`;`)
  await db.run(sql`ALTER TABLE \`sections_blocks_price_single\` DROP COLUMN \`guarantee_title_tag\`;`)
  await db.run(sql`ALTER TABLE \`sections_blocks_plan\` DROP COLUMN \`name_tag\`;`)
  await db.run(sql`ALTER TABLE \`sections_blocks_plan\` DROP COLUMN \`guarantee_title_tag\`;`)
  await db.run(sql`ALTER TABLE \`sections_blocks_process_steps\` DROP COLUMN \`tag\`;`)
}
