/* Generated by scripts/gen-catalog.mjs (pnpm catalog:build). */
import {VStack} from '@astryxdesign/core/Stack';
import React from 'react';

import QuoteCardShowcase from '../../_showcases/QuoteCardShowcase';
import {ComponentNav} from '../../_ui/ComponentNav';
import {ShowcaseBlock} from '../../_ui/ShowcaseBlock';

export const metadata = {title: 'Quote Card — Design system Vidomia'};

export default function Page() {
  return (
    <VStack gap={8}>
      <ShowcaseBlock name="QuoteCard" id="quote-card" doc={null} dressed category="Contenu">
        <QuoteCardShowcase />
      </ShowcaseBlock>
      <ComponentNav category="contenu" current="quote-card" />
    </VStack>
  );
}
