import type {Block, Field} from 'payload';

import {maxSpan, minSpan} from '@/components/content-specs';
import type {ContentBlock} from '@/fields/sections/contentBlock';
import {cardBlockText as t} from '../../i18n/admin/blocks';
import {ADMIN_LANGUAGE_CODES, type Text} from '../../i18n/admin/languages';
import {iconField} from '../iconField';
import {tagField} from '../tagField';
import {loremWords} from '../lorem/words';
import {linkGroup} from '../shared';

/**
 * The « Carte » blocks of a column: the Card component, « bloc » preset, split into
 * eight blocks so that Payload's picker shows each variant as an image
 * (public/apercus/<slug>.png, generated by `pnpm previews:build`):
 *   image media, icon, number or title only × plain card or clickable card.
 * The eight blocks share the same fields (title, text); the clickable variant adds
 * the action button. Span: 3 to 5 columns (span registry, type « card »).
 */
export type CardMediaKind = 'image' | 'icon' | 'number' | 'title';

const MEDIA: {kind: CardMediaKind; slug: string; label: Text; fields: Field[]; sample?: Record<string, unknown>}[] = [
  {kind: 'image', slug: 'Image', label: t.media.image, fields: [{name: 'image', type: 'upload', relationTo: 'media', label: t.fields.image, required: true}]},
  {kind: 'icon', slug: 'Icon', label: t.media.icon, fields: [iconField({name: 'iconKey', label: t.fields.icon, required: true})], sample: {iconKey: 'shield'}},
  {
    kind: 'number',
    slug: 'Number',
    label: t.media.number,
    fields: [
      {
        type: 'row',
        fields: [
          {name: 'prefix', type: 'text', label: t.fields.prefix, localized: true, admin: {width: '25%'}},
          {name: 'value', type: 'text', label: t.fields.value, required: true, admin: {width: '50%'}},
          {name: 'suffix', type: 'text', label: t.fields.suffix, localized: true, admin: {width: '25%'}},
        ],
      },
    ],
    sample: {prefix: '+', value: '34', suffix: '%'},
  },
  {kind: 'title', slug: 'Title', label: t.media.title, fields: []},
];

const COMMON: Field[] = [
  {
    type: 'row',
    fields: [
      {name: 'title', type: 'text', label: t.fields.title, required: true, localized: true, admin: {width: '70%'}},
      tagField({defaultValue: 'h3', width: '30%'}),
    ],
  },
  {name: 'text', type: 'textarea', label: t.fields.text, localized: true, admin: {rows: 3}},
];

/**
 * Where the card's content sits when the card is taller than it (beside an image card or a tall
 * block, the cards of a row sharing one height). Not on the image variant: its image is at the top.
 */
const V_ALIGN: Field = {
  name: 'vAlign',
  type: 'select',
  label: t.fields.vAlign,
  defaultValue: 'start',
  options: [
    {label: t.fields.vAlignStart, value: 'start'},
    {label: t.fields.vAlignCenter, value: 'center'},
    {label: t.fields.vAlignEnd, value: 'end'},
  ],
};

/** Builds a Text by computing each admin language's value. */
const mapText = (build: (lang: keyof Text) => string): Text =>
  Object.fromEntries(ADMIN_LANGUAGE_CODES.map((lang) => [lang, build(lang)])) as Text;

export const CARD_BLOCKS: ContentBlock[] = [];
/** Minimum column width of a card (span registry of the catalogue). */
const CARD_MIN_SPAN = minSpan({type: 'card'});
/** Maximum column width of a card (same registry). */
const CARD_MAX_SPAN = maxSpan({type: 'card'});
/** block slug → variant (media, clickable) and short label for the admin */
export const CARD_VARIANTS: Record<string, {media: CardMediaKind; clickable: boolean; label: Text}> = {};

for (const clickable of [false, true]) {
  for (const m of MEDIA) {
    const slug = `card${m.slug}${clickable ? 'Link' : ''}`;
    const name = clickable ? t.names.clickableCard : t.names.card;
    const label = mapText((lang) => `${name[lang]} · ${m.label[lang]}`);
    CARD_VARIANTS[slug] = {media: m.kind, clickable, label};
    const block: Block = {
      slug,
      labels: {singular: label, plural: mapText((lang) => `${label[lang]}${t.pluralSuffix[lang]}`)},
      imageURL: `/apercus/${slug}.png`,
      fields: [...m.fields, ...COMMON, ...(m.kind === 'image' ? [] : [{...V_ALIGN}]), ...(clickable ? [linkGroup('cta', t.fields.cta, {required: true})] : [])],
    };
    // fills the row height: cards side by side, or beside another box, share one height
    // placeholder texts when the card is placed from the builder's library (the image is chosen by the editor)
    const sample = {...m.sample, title: 'Lorem ipsum dolor', text: loremWords(16), ...(clickable ? {'cta.label': 'Lorem ipsum', 'cta.href': '#'} : null)};
    // the parts of the Card component edited in place in the builder's preview → the block's fields
    const parts = {title: 'title', text: 'text', action: 'cta.label', image: 'image', icon: 'iconKey'};
    CARD_BLOCKS.push({block, minSpan: CARD_MIN_SPAN, maxSpan: CARD_MAX_SPAN, fill: true, sample, parts});
  }
}

export const CARD_SLUGS = Object.keys(CARD_VARIANTS);
