/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/silos/orbita-violet.ts
 * Command: astryx theme build src/theme/silos/orbita-violet.ts
 * CLI: @astryxdesign/cli@0.5.4
 * Core: @astryxdesign/core@0.5.4
 */

/// <reference path="./orbita-violet.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const orbitaVioletTheme: DefinedTheme;
