/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/silos/orbita-orange.ts
 * Command: astryx theme build src/theme/silos/orbita-orange.ts
 * CLI: @astryxdesign/cli@0.5.4
 * Core: @astryxdesign/core@0.5.4
 */

/// <reference path="./orbita-orange.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const orbitaOrangeTheme: DefinedTheme;
