/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/silos/orbita-orange.ts
 * Command: astryx theme build src/theme/silos/orbita-orange.ts
 * CLI: @astryxdesign/cli@0.5.4
 * Core: @astryxdesign/core@0.5.4
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Heading' {
  interface HeadingTypeMap {
    'display-1': true;
    'display-2': true;
    'display-3': true;
    'card': true;
  }
}

declare module '@astryxdesign/core/Button' {
  interface ButtonVariantMap {
    'high': true;
    'ink': true;
  }
}

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'chip': true;
    'chip-high': true;
    'chip-accent': true;
    'chip-cat': true;
    'chip-live': true;
    'chip-live-dark': true;
    'chip-danger': true;
  }
}
