/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/silos/orbita-ambre.ts
 * Command: astryx theme build src/theme/silos/orbita-ambre.ts
 * CLI: @astryxdesign/cli@0.5.4
 * Core: @astryxdesign/core@0.5.4
 */

/**
 * orbita-ambre theme — built by `pnpm exec astryx theme build`
 * Import the CSS file alongside this module:
 *
 *   import { orbitaAmbreTheme } from './orbita-ambre';
 *   import './orbita-ambre.css';
 */
export const orbitaAmbreTheme = {
  name: 'orbita-ambre',
  __built: true,
  tokens: {
    "--color-accent": "light-dark(#C99016, #C99016)",
    "--color-accent-muted": "light-dark(color-mix(in srgb, var(--color-accent) 20%, transparent), color-mix(in srgb, var(--color-accent) 25%, transparent))",
    "--color-on-accent": "light-dark(#FFFFFF, #FFFFFF)",
    "--color-neutral": "light-dark(#1F1B151A, #E8E1D933)",
    "--color-background-surface": "light-dark(#FFFFFF, color-mix(in srgb, #241B06 82%, #000000))",
    "--color-background-body": "light-dark(#FBF6EC, #241B06)",
    "--color-overlay": "light-dark(color-mix(in srgb, #C99016 26%, rgba(28,38,68,.4)), color-mix(in srgb, #241B06 58%, rgba(7,9,26,.6)))",
    "--color-overlay-hover": "light-dark(#1F1B150D, #FFFFFF0D)",
    "--color-overlay-pressed": "light-dark(#1F1B151A, #FFFFFF1A)",
    "--color-background-muted": "light-dark(#F3E7CC, rgba(255,255,255,.06))",
    "--color-text-primary": "light-dark(#0C1424, #FFFFFF)",
    "--color-text-secondary": "light-dark(#3A4456, rgba(255,255,255,.72))",
    "--color-text-disabled": "light-dark(#6A7486, rgba(255,255,255,.4))",
    "--color-text-accent": "light-dark(#C99016, #DAB461)",
    "--color-icon-accent": "light-dark(#C99016, #DAB461)",
    "--color-icon-primary": "light-dark(#0C1424, #FFFFFF)",
    "--color-icon-secondary": "light-dark(#3A4456, rgba(255,255,255,.72))",
    "--color-icon-disabled": "light-dark(#6A7486, rgba(255,255,255,.4))",
    "--color-background-card": "light-dark(#FFFFFF, color-mix(in srgb, #241B06 82%, #000000))",
    "--color-background-popover": "light-dark(#FFFFFF, color-mix(in srgb, #241B06 88%, #FFFFFF))",
    "--color-background-inverted": "light-dark(#241B06, #FFFFFF)",
    "--color-border": "light-dark(#E1E6F1, rgba(255,255,255,.14))",
    "--color-border-emphasized": "light-dark(#CCD4E4, rgba(255,255,255,.3))",
    "--color-skeleton": "light-dark(#E1E6F1, rgba(255,255,255,.12))",
    "--color-track": "light-dark(#CCD4E4, rgba(255,255,255,.2))",
    "--color-shadow": "light-dark(rgba(12,20,40,.07), rgba(0,0,0,.4))",
    "--color-tint-hover": "light-dark(black, white)",
    "--font-size-4xs": "0.375rem",
    "--font-size-3xs": "0.4375rem",
    "--font-size-2xs": "0.5625rem",
    "--font-size-xs": "0.625rem",
    "--font-size-sm": "0.8125rem",
    "--font-size-base": "0.9375rem",
    "--font-size-lg": "1.125rem",
    "--font-size-xl": "1.375rem",
    "--font-size-2xl": "1.625rem",
    "--font-size-3xl": "1.9375rem",
    "--font-size-4xl": "2.3125rem",
    "--font-size-5xl": "2.8125rem",
    "--text-heading-1-size": "var(--font-size-2xl)",
    "--text-heading-1-weight": "var(--font-weight-bold)",
    "--text-heading-1-leading": "1.3846",
    "--text-heading-2-size": "var(--font-size-xl)",
    "--text-heading-2-weight": "var(--font-weight-bold)",
    "--text-heading-2-leading": "1.4545",
    "--text-heading-3-size": "var(--font-size-lg)",
    "--text-heading-3-weight": "var(--font-weight-bold)",
    "--text-heading-3-leading": "1.5556",
    "--text-heading-4-size": "var(--font-size-base)",
    "--text-heading-4-weight": "var(--font-weight-semibold)",
    "--text-heading-4-leading": "1.6",
    "--text-heading-5-size": "var(--font-size-sm)",
    "--text-heading-5-weight": "var(--font-weight-semibold)",
    "--text-heading-5-leading": "1.5385",
    "--text-heading-6-size": "var(--font-size-xs)",
    "--text-heading-6-weight": "var(--font-weight-semibold)",
    "--text-heading-6-leading": "1.6",
    "--text-body-size": "var(--font-size-base)",
    "--text-body-weight": "var(--font-weight-normal)",
    "--text-body-leading": "1.6",
    "--text-large-size": "1.125rem",
    "--text-large-weight": "var(--font-weight-semibold)",
    "--text-large-leading": "1.62",
    "--text-label-size": "var(--font-size-base)",
    "--text-label-weight": "var(--font-weight-medium)",
    "--text-label-leading": "1.6",
    "--text-code-size": "var(--font-size-base)",
    "--text-code-weight": "var(--font-weight-normal)",
    "--text-code-leading": "1.6",
    "--text-supporting-size": "var(--font-size-sm)",
    "--text-supporting-weight": "var(--font-weight-normal)",
    "--text-supporting-leading": "1.5385",
    "--text-display-1-size": "clamp(42px, 6vw, 76px)",
    "--text-display-1-weight": "800",
    "--text-display-1-leading": "1.04",
    "--text-display-2-size": "clamp(40px, 5vw, 64px)",
    "--text-display-2-weight": "800",
    "--text-display-2-leading": "1.04",
    "--text-display-3-size": "clamp(32px, 4.4vw, 54px)",
    "--text-display-3-weight": "800",
    "--text-display-3-leading": "1.08",
    "--radius-none": "0px",
    "--radius-inner": "0px",
    "--radius-element": "0px",
    "--radius-container": "0px",
    "--radius-page": "0px",
    "--radius-chat": "0px",
    "--radius-full": "9999px",
    "--duration-fast-min": "150ms",
    "--duration-fast": "200ms",
    "--duration-fast-max": "265ms",
    "--duration-medium-min": "190ms",
    "--duration-medium": "250ms",
    "--duration-medium-max": "335ms",
    "--duration-slow-min": "375ms",
    "--duration-slow": "500ms",
    "--duration-slow-max": "665ms",
    "--ease-standard": "ease-in-out",
    "--font-family-body": "var(--font-geist), system-ui, sans-serif",
    "--font-family-heading": "var(--font-schibsted), system-ui, sans-serif",
    "--font-family-code": "\"SF Mono\", ui-monospace, Menlo, monospace",
    "--size-element-sm": "36px",
    "--size-element-md": "48px",
    "--size-element-lg": "56px",
    "--color-error": "light-dark(#D0342C, #F0655D)",
    "--color-error-muted": "light-dark(rgba(208,52,44,.10), rgba(240,101,93,.18))",
    "--color-success": "light-dark(#1F8A5B, #3FB57F)",
    "--color-success-muted": "light-dark(rgba(31,138,91,.10), rgba(63,181,127,.18))",
    "--color-warning": "light-dark(#C7972E, #E0B04A)",
    "--color-warning-muted": "light-dark(rgba(199,151,46,.12), rgba(224,176,74,.18))",
    "--shadow-low": "0 2px 6px var(--color-shadow)",
    "--shadow-med": "0 2px 6px rgba(12,20,40,.05), 0 14px 36px var(--color-shadow)",
    "--shadow-high": "0 6px 14px rgba(12,20,40,.06), 0 28px 64px var(--color-shadow)",
    "--focus-outline-color": "var(--color-accent)",
    "--focus-outline-offset": "2px",
    "--font-family-serif": "var(--font-cormorant), Georgia, serif",
    "--icon-stroke-width": "1.25",
    "--color-highlight": "light-dark(#4DA3F0, #4DA3F0)",
    "--color-highlight-deep": "light-dark(#1F6FCC, #4DA3F0)",
    "--color-highlight-muted": "light-dark(color-mix(in srgb, #4DA3F0 14%, transparent), color-mix(in srgb, #4DA3F0 22%, transparent))",
    "--color-editorial": "light-dark(#C7972E, #C7972E)",
    "--color-editorial-deep": "light-dark(#A37B1F, #C7972E)",
    "--color-night": "light-dark(#241B06, #241B06)",
    "--color-background-light": "light-dark(#FAF4E8, rgba(255,255,255,.03))",
    "--color-accent-deep": "light-dark(#9E6F08, #C99016)"
  },
  components: {
    "heading": {
      "level:1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-1-size)",
        "fontWeight": "var(--text-heading-1-weight)",
        "lineHeight": "var(--text-heading-1-leading)"
      },
      "level:2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-2-size)",
        "fontWeight": "var(--text-heading-2-weight)",
        "lineHeight": "var(--text-heading-2-leading)"
      },
      "level:3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-3-size)",
        "fontWeight": "var(--text-heading-3-weight)",
        "lineHeight": "var(--text-heading-3-leading)"
      },
      "level:4": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-4-size)",
        "fontWeight": "var(--text-heading-4-weight)",
        "lineHeight": "var(--text-heading-4-leading)"
      },
      "level:5": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-5-size)",
        "fontWeight": "var(--text-heading-5-weight)",
        "lineHeight": "var(--text-heading-5-leading)"
      },
      "level:6": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-6-size)",
        "fontWeight": "var(--text-heading-6-weight)",
        "lineHeight": "var(--text-heading-6-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)",
        "letterSpacing": "-0.025em"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)",
        "letterSpacing": "-0.025em"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)",
        "letterSpacing": "-0.02em"
      },
      "type:card": {
        "fontSize": "18px",
        "fontWeight": "var(--font-weight-bold)",
        "lineHeight": "1.3",
        "letterSpacing": "-0.015em"
      }
    },
    "text": {
      "type:body": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-body-size)",
        "lineHeight": "var(--text-body-leading)"
      },
      "type:large": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-large-size)",
        "lineHeight": "var(--text-large-leading)"
      },
      "type:label": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-label-size)",
        "lineHeight": "var(--text-label-leading)"
      },
      "type:code": {
        "fontFamily": "var(--font-family-code)",
        "fontSize": "var(--text-code-size)",
        "lineHeight": "var(--text-code-leading)"
      },
      "type:supporting": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-supporting-size)",
        "lineHeight": "var(--text-supporting-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      },
      "type:eyebrow": {
        "fontSize": "0.72rem",
        "fontWeight": "var(--font-weight-semibold)",
        "letterSpacing": "0.16em",
        "textTransform": "uppercase",
        "lineHeight": "1.4",
        "color": "var(--color-editorial)"
      },
      "type:serif": {
        "fontFamily": "var(--font-family-serif)",
        "fontStyle": "italic",
        "fontWeight": "600",
        "color": "var(--color-accent)",
        "fontSize": "inherit",
        "lineHeight": "inherit",
        "letterSpacing": "-0.01em"
      },
      "type:number": {
        "fontFamily": "var(--font-family-heading)",
        "fontWeight": "800",
        "fontSize": "clamp(40px, 3.4vw, 52px)",
        "lineHeight": "1",
        "letterSpacing": "-0.03em",
        "color": "var(--color-text-accent)"
      },
      "type:result": {
        "fontSize": "12px",
        "fontWeight": "var(--font-weight-semibold)",
        "letterSpacing": "0.02em",
        "color": "light-dark(var(--color-text-accent), var(--color-highlight))",
        "whiteSpace": "nowrap"
      },
      "type:date": {
        "fontSize": "12px",
        "color": "var(--color-text-disabled)",
        "whiteSpace": "nowrap"
      },
      "type:tag": {
        "fontSize": "0.7rem",
        "fontWeight": "var(--font-weight-medium)",
        "letterSpacing": "0.14em",
        "textTransform": "uppercase",
        "lineHeight": "1.4"
      }
    },
    "button": {
      "base": {
        "fontWeight": "var(--font-weight-semibold)",
        "position": "relative",
        "overflow": "visible",
        "transition": "background-color var(--duration-medium) var(--ease-standard), border-color var(--duration-medium) var(--ease-standard), color var(--duration-medium) var(--ease-standard), box-shadow var(--duration-medium) var(--ease-standard)"
      },
      "size:sm": {
        "paddingInline": "var(--spacing-4)",
        "gap": "var(--spacing-2)"
      },
      "size:md": {
        "paddingInline": "var(--spacing-6)",
        "gap": "var(--spacing-3)"
      },
      "size:lg": {
        "paddingInline": "var(--spacing-8)",
        "gap": "var(--spacing-4)",
        "fontSize": "var(--font-size-lg)"
      },
      "variant:primary": {
        "boxShadow": "0 10px 24px var(--color-accent-muted)",
        ":hover": {
          "backgroundColor": "var(--color-accent-deep)"
        }
      },
      "variant:ghost": {
        "borderWidth": "var(--border-width)",
        "borderStyle": "solid",
        "borderColor": "light-dark(var(--color-border-emphasized), rgba(255,255,255,.5))",
        "backgroundColor": "light-dark(var(--color-background-surface), rgba(255,255,255,.04))",
        "color": "light-dark(var(--color-text-accent), #FFFFFF)",
        ":hover": {
          "borderColor": "light-dark(var(--color-accent), #FFFFFF)",
          "color": "light-dark(var(--color-accent), var(--color-accent))",
          "backgroundColor": "light-dark(var(--color-background-surface), #FFFFFF)"
        }
      },
      "variant:high": {
        "backgroundColor": "var(--color-highlight)",
        "color": "var(--color-night)",
        "boxShadow": "0 10px 26px var(--color-highlight-muted)",
        ":hover": {
          "backgroundColor": "var(--color-highlight-deep)"
        }
      }
    },
    "icon-button": {
      "base": {
        "transition": "background-color var(--duration-medium) var(--ease-standard), border-color var(--duration-medium) var(--ease-standard), color var(--duration-medium) var(--ease-standard)"
      }
    },
    "text-input": {
      "base": {
        "borderColor": "var(--color-border-emphasized)",
        "backgroundColor": "var(--color-background-surface)",
        "transition": "border-color var(--duration-medium) var(--ease-standard), box-shadow var(--duration-medium) var(--ease-standard)",
        ":focus-within": {
          "borderColor": "light-dark(var(--color-accent), var(--color-highlight))",
          "boxShadow": "0 0 0 3px light-dark(var(--color-accent-muted), var(--color-highlight-muted))"
        }
      },
      "disabled": {
        "backgroundColor": "var(--color-background-muted)",
        "borderColor": "var(--color-border)",
        "color": "var(--color-text-disabled)"
      },
      "status:error": {
        "borderColor": "var(--color-error)",
        "boxShadow": "0 0 0 3px var(--color-error-muted)",
        ":focus-within": {
          "borderColor": "var(--color-error)",
          "boxShadow": "0 0 0 3px var(--color-error-muted)"
        }
      },
      "status:success": {
        "borderColor": "var(--color-success)",
        "boxShadow": "0 0 0 3px var(--color-success-muted)",
        ":focus-within": {
          "borderColor": "var(--color-success)",
          "boxShadow": "0 0 0 3px var(--color-success-muted)"
        }
      },
      "status:warning": {
        "borderColor": "var(--color-warning)",
        "boxShadow": "0 0 0 3px var(--color-warning-muted)",
        ":focus-within": {
          "borderColor": "var(--color-warning)",
          "boxShadow": "0 0 0 3px var(--color-warning-muted)"
        }
      }
    },
    "text-area": {
      "base": {
        "borderColor": "var(--color-border-emphasized)",
        "backgroundColor": "var(--color-background-surface)",
        "transition": "border-color var(--duration-medium) var(--ease-standard), box-shadow var(--duration-medium) var(--ease-standard)",
        ":focus-within": {
          "borderColor": "light-dark(var(--color-accent), var(--color-highlight))",
          "boxShadow": "0 0 0 3px light-dark(var(--color-accent-muted), var(--color-highlight-muted))"
        }
      },
      "disabled": {
        "backgroundColor": "var(--color-background-muted)",
        "borderColor": "var(--color-border)",
        "color": "var(--color-text-disabled)"
      },
      "status:error": {
        "borderColor": "var(--color-error)",
        "boxShadow": "0 0 0 3px var(--color-error-muted)",
        ":focus-within": {
          "borderColor": "var(--color-error)",
          "boxShadow": "0 0 0 3px var(--color-error-muted)"
        }
      },
      "status:success": {
        "borderColor": "var(--color-success)",
        "boxShadow": "0 0 0 3px var(--color-success-muted)",
        ":focus-within": {
          "borderColor": "var(--color-success)",
          "boxShadow": "0 0 0 3px var(--color-success-muted)"
        }
      },
      "status:warning": {
        "borderColor": "var(--color-warning)",
        "boxShadow": "0 0 0 3px var(--color-warning-muted)",
        ":focus-within": {
          "borderColor": "var(--color-warning)",
          "boxShadow": "0 0 0 3px var(--color-warning-muted)"
        }
      }
    },
    "number-input": {
      "base": {
        "borderColor": "var(--color-border-emphasized)",
        "backgroundColor": "var(--color-background-surface)",
        "transition": "border-color var(--duration-medium) var(--ease-standard), box-shadow var(--duration-medium) var(--ease-standard)",
        ":focus-within": {
          "borderColor": "light-dark(var(--color-accent), var(--color-highlight))",
          "boxShadow": "0 0 0 3px light-dark(var(--color-accent-muted), var(--color-highlight-muted))"
        }
      },
      "disabled": {
        "backgroundColor": "var(--color-background-muted)",
        "borderColor": "var(--color-border)",
        "color": "var(--color-text-disabled)"
      },
      "status:error": {
        "borderColor": "var(--color-error)",
        "boxShadow": "0 0 0 3px var(--color-error-muted)",
        ":focus-within": {
          "borderColor": "var(--color-error)",
          "boxShadow": "0 0 0 3px var(--color-error-muted)"
        }
      },
      "status:success": {
        "borderColor": "var(--color-success)",
        "boxShadow": "0 0 0 3px var(--color-success-muted)",
        ":focus-within": {
          "borderColor": "var(--color-success)",
          "boxShadow": "0 0 0 3px var(--color-success-muted)"
        }
      },
      "status:warning": {
        "borderColor": "var(--color-warning)",
        "boxShadow": "0 0 0 3px var(--color-warning-muted)",
        ":focus-within": {
          "borderColor": "var(--color-warning)",
          "boxShadow": "0 0 0 3px var(--color-warning-muted)"
        }
      }
    },
    "selector": {
      "base": {
        "borderColor": "var(--color-border-emphasized)",
        "backgroundColor": "var(--color-background-surface)",
        "transition": "border-color var(--duration-medium) var(--ease-standard), box-shadow var(--duration-medium) var(--ease-standard)",
        ":focus-within": {
          "borderColor": "light-dark(var(--color-accent), var(--color-highlight))",
          "boxShadow": "0 0 0 3px light-dark(var(--color-accent-muted), var(--color-highlight-muted))"
        }
      },
      "disabled": {
        "backgroundColor": "var(--color-background-muted)",
        "borderColor": "var(--color-border)",
        "color": "var(--color-text-disabled)"
      },
      "status:error": {
        "borderColor": "var(--color-error)",
        "boxShadow": "0 0 0 3px var(--color-error-muted)",
        ":focus-within": {
          "borderColor": "var(--color-error)",
          "boxShadow": "0 0 0 3px var(--color-error-muted)"
        }
      },
      "status:success": {
        "borderColor": "var(--color-success)",
        "boxShadow": "0 0 0 3px var(--color-success-muted)",
        ":focus-within": {
          "borderColor": "var(--color-success)",
          "boxShadow": "0 0 0 3px var(--color-success-muted)"
        }
      },
      "status:warning": {
        "borderColor": "var(--color-warning)",
        "boxShadow": "0 0 0 3px var(--color-warning-muted)",
        ":focus-within": {
          "borderColor": "var(--color-warning)",
          "boxShadow": "0 0 0 3px var(--color-warning-muted)"
        }
      }
    },
    "multi-selector": {
      "base": {
        "borderColor": "var(--color-border-emphasized)",
        "backgroundColor": "var(--color-background-surface)",
        "transition": "border-color var(--duration-medium) var(--ease-standard), box-shadow var(--duration-medium) var(--ease-standard)",
        ":focus-within": {
          "borderColor": "light-dark(var(--color-accent), var(--color-highlight))",
          "boxShadow": "0 0 0 3px light-dark(var(--color-accent-muted), var(--color-highlight-muted))"
        }
      },
      "disabled": {
        "backgroundColor": "var(--color-background-muted)",
        "borderColor": "var(--color-border)",
        "color": "var(--color-text-disabled)"
      },
      "status:error": {
        "borderColor": "var(--color-error)",
        "boxShadow": "0 0 0 3px var(--color-error-muted)",
        ":focus-within": {
          "borderColor": "var(--color-error)",
          "boxShadow": "0 0 0 3px var(--color-error-muted)"
        }
      },
      "status:success": {
        "borderColor": "var(--color-success)",
        "boxShadow": "0 0 0 3px var(--color-success-muted)",
        ":focus-within": {
          "borderColor": "var(--color-success)",
          "boxShadow": "0 0 0 3px var(--color-success-muted)"
        }
      },
      "status:warning": {
        "borderColor": "var(--color-warning)",
        "boxShadow": "0 0 0 3px var(--color-warning-muted)",
        ":focus-within": {
          "borderColor": "var(--color-warning)",
          "boxShadow": "0 0 0 3px var(--color-warning-muted)"
        }
      }
    },
    "typeahead": {
      "base": {
        "borderColor": "var(--color-border-emphasized)",
        "backgroundColor": "var(--color-background-surface)",
        "transition": "border-color var(--duration-medium) var(--ease-standard), box-shadow var(--duration-medium) var(--ease-standard)",
        ":focus-within": {
          "borderColor": "light-dark(var(--color-accent), var(--color-highlight))",
          "boxShadow": "0 0 0 3px light-dark(var(--color-accent-muted), var(--color-highlight-muted))"
        }
      },
      "disabled": {
        "backgroundColor": "var(--color-background-muted)",
        "borderColor": "var(--color-border)",
        "color": "var(--color-text-disabled)"
      },
      "status:error": {
        "borderColor": "var(--color-error)",
        "boxShadow": "0 0 0 3px var(--color-error-muted)",
        ":focus-within": {
          "borderColor": "var(--color-error)",
          "boxShadow": "0 0 0 3px var(--color-error-muted)"
        }
      },
      "status:success": {
        "borderColor": "var(--color-success)",
        "boxShadow": "0 0 0 3px var(--color-success-muted)",
        ":focus-within": {
          "borderColor": "var(--color-success)",
          "boxShadow": "0 0 0 3px var(--color-success-muted)"
        }
      },
      "status:warning": {
        "borderColor": "var(--color-warning)",
        "boxShadow": "0 0 0 3px var(--color-warning-muted)",
        ":focus-within": {
          "borderColor": "var(--color-warning)",
          "boxShadow": "0 0 0 3px var(--color-warning-muted)"
        }
      }
    },
    "tokenizer": {
      "base": {
        "borderColor": "var(--color-border-emphasized)",
        "backgroundColor": "var(--color-background-surface)",
        "transition": "border-color var(--duration-medium) var(--ease-standard), box-shadow var(--duration-medium) var(--ease-standard)",
        ":focus-within": {
          "borderColor": "light-dark(var(--color-accent), var(--color-highlight))",
          "boxShadow": "0 0 0 3px light-dark(var(--color-accent-muted), var(--color-highlight-muted))"
        }
      },
      "disabled": {
        "backgroundColor": "var(--color-background-muted)",
        "borderColor": "var(--color-border)",
        "color": "var(--color-text-disabled)"
      },
      "status:error": {
        "borderColor": "var(--color-error)",
        "boxShadow": "0 0 0 3px var(--color-error-muted)",
        ":focus-within": {
          "borderColor": "var(--color-error)",
          "boxShadow": "0 0 0 3px var(--color-error-muted)"
        }
      },
      "status:success": {
        "borderColor": "var(--color-success)",
        "boxShadow": "0 0 0 3px var(--color-success-muted)",
        ":focus-within": {
          "borderColor": "var(--color-success)",
          "boxShadow": "0 0 0 3px var(--color-success-muted)"
        }
      },
      "status:warning": {
        "borderColor": "var(--color-warning)",
        "boxShadow": "0 0 0 3px var(--color-warning-muted)",
        ":focus-within": {
          "borderColor": "var(--color-warning)",
          "boxShadow": "0 0 0 3px var(--color-warning-muted)"
        }
      }
    },
    "date-input": {
      "base": {
        "borderColor": "var(--color-border-emphasized)",
        "backgroundColor": "var(--color-background-surface)",
        "transition": "border-color var(--duration-medium) var(--ease-standard), box-shadow var(--duration-medium) var(--ease-standard)",
        ":focus-within": {
          "borderColor": "light-dark(var(--color-accent), var(--color-highlight))",
          "boxShadow": "0 0 0 3px light-dark(var(--color-accent-muted), var(--color-highlight-muted))"
        }
      },
      "disabled": {
        "backgroundColor": "var(--color-background-muted)",
        "borderColor": "var(--color-border)",
        "color": "var(--color-text-disabled)"
      },
      "status:error": {
        "borderColor": "var(--color-error)",
        "boxShadow": "0 0 0 3px var(--color-error-muted)",
        ":focus-within": {
          "borderColor": "var(--color-error)",
          "boxShadow": "0 0 0 3px var(--color-error-muted)"
        }
      },
      "status:success": {
        "borderColor": "var(--color-success)",
        "boxShadow": "0 0 0 3px var(--color-success-muted)",
        ":focus-within": {
          "borderColor": "var(--color-success)",
          "boxShadow": "0 0 0 3px var(--color-success-muted)"
        }
      },
      "status:warning": {
        "borderColor": "var(--color-warning)",
        "boxShadow": "0 0 0 3px var(--color-warning-muted)",
        ":focus-within": {
          "borderColor": "var(--color-warning)",
          "boxShadow": "0 0 0 3px var(--color-warning-muted)"
        }
      }
    },
    "selector-popup": {
      "base": {
        "borderRadius": "0",
        "borderWidth": "var(--border-width)",
        "borderStyle": "solid",
        "borderColor": "var(--color-border)",
        "boxShadow": "0 26px 60px light-dark(rgba(12,20,40,.16), rgba(0,0,0,.5))",
        "padding": "var(--spacing-1-5)"
      }
    },
    "multi-selector-popup": {
      "base": {
        "borderRadius": "0",
        "borderWidth": "var(--border-width)",
        "borderStyle": "solid",
        "borderColor": "var(--color-border)",
        "boxShadow": "0 26px 60px light-dark(rgba(12,20,40,.16), rgba(0,0,0,.5))",
        "padding": "var(--spacing-1-5)"
      }
    },
    "typeahead-dropdown": {
      "base": {
        "borderRadius": "0",
        "borderWidth": "var(--border-width)",
        "borderStyle": "solid",
        "borderColor": "var(--color-border)",
        "boxShadow": "0 26px 60px light-dark(rgba(12,20,40,.16), rgba(0,0,0,.5))",
        "padding": "var(--spacing-1-5)"
      }
    },
    "popover-surface": {
      "base": {
        "borderRadius": "0",
        "borderWidth": "var(--border-width)",
        "borderStyle": "solid",
        "borderColor": "var(--color-border)",
        "boxShadow": "0 26px 60px light-dark(rgba(12,20,40,.16), rgba(0,0,0,.5))",
        "padding": "var(--spacing-1-5)"
      }
    },
    "selector-option-row": {
      "base": {
        "borderRadius": "0",
        "color": "var(--color-text-secondary)",
        "transition": "background-color var(--duration-medium) var(--ease-standard), color var(--duration-medium) var(--ease-standard)",
        ":hover": {
          "backgroundColor": "light-dark(var(--color-accent-muted), rgba(255,255,255,.08))",
          "color": "var(--color-text-primary)"
        }
      },
      "selected": {
        "color": "light-dark(var(--color-text-accent), var(--color-highlight))",
        "fontWeight": "var(--font-weight-semibold)"
      }
    },
    "multi-selector-option": {
      "base": {
        "borderRadius": "0",
        "color": "var(--color-text-secondary)",
        "transition": "background-color var(--duration-medium) var(--ease-standard), color var(--duration-medium) var(--ease-standard)",
        ":hover": {
          "backgroundColor": "light-dark(var(--color-accent-muted), rgba(255,255,255,.08))",
          "color": "var(--color-text-primary)"
        }
      },
      "selected": {
        "color": "light-dark(var(--color-text-accent), var(--color-highlight))",
        "fontWeight": "var(--font-weight-semibold)"
      }
    },
    "typeahead-item": {
      "base": {
        "borderRadius": "0",
        "color": "var(--color-text-secondary)",
        "transition": "background-color var(--duration-medium) var(--ease-standard), color var(--duration-medium) var(--ease-standard)",
        ":hover": {
          "backgroundColor": "light-dark(var(--color-accent-muted), rgba(255,255,255,.08))",
          "color": "var(--color-text-primary)"
        }
      },
      "selected": {
        "color": "light-dark(var(--color-text-accent), var(--color-highlight))",
        "fontWeight": "var(--font-weight-semibold)"
      }
    },
    "selector-search": {
      "base": {
        "borderBottom": "var(--border-width) solid var(--color-border)"
      }
    },
    "multi-selector-search": {
      "base": {
        "borderBottom": "var(--border-width) solid var(--color-border)"
      }
    },
    "tab-list": {
      "base": {
        "height": "auto",
        "fontFamily": "var(--font-family-body)",
        "backgroundColor": "light-dark(var(--color-background-surface), var(--color-background-card))",
        "borderWidth": "var(--border-width)",
        "borderStyle": "solid",
        "borderColor": "light-dark(var(--color-border), rgba(255,255,255,.15))"
      }
    },
    "tab-strip": {
      "base": {
        "height": "auto",
        "gap": "0"
      }
    },
    "tab": {
      "base": {
        "height": "auto",
        "padding": "18px 22px",
        "gap": "12px",
        "fontSize": "15px",
        "fontWeight": "var(--font-weight-semibold)",
        "lineHeight": "1.3",
        "textAlign": "center",
        "justifyContent": "center",
        "color": "light-dark(var(--color-text-secondary), rgba(255,255,255,.8))",
        "borderRadius": "0",
        "transition": "color var(--duration-medium) var(--ease-standard), background-color var(--duration-medium) var(--ease-standard)",
        ":hover": {
          "color": "light-dark(var(--color-text-primary), #FFFFFF)",
          "backgroundColor": "light-dark(var(--color-accent-muted), rgba(255,255,255,.06))"
        }
      },
      "selected": {
        "color": "light-dark(var(--color-text-accent), var(--color-highlight))"
      }
    },
    "tab-menu": {
      "base": {
        "height": "auto",
        "padding": "18px 22px",
        "gap": "12px",
        "fontSize": "15px",
        "fontWeight": "var(--font-weight-semibold)",
        "lineHeight": "1.3",
        "textAlign": "center",
        "justifyContent": "center",
        "color": "light-dark(var(--color-text-secondary), rgba(255,255,255,.8))",
        "borderRadius": "0",
        "transition": "color var(--duration-medium) var(--ease-standard), background-color var(--duration-medium) var(--ease-standard)",
        ":hover": {
          "color": "light-dark(var(--color-text-primary), #FFFFFF)",
          "backgroundColor": "light-dark(var(--color-accent-muted), rgba(255,255,255,.06))"
        }
      },
      "selected": {
        "color": "light-dark(var(--color-text-accent), var(--color-highlight))"
      }
    },
    "tab-indicator": {
      "base": {
        "left": "0",
        "right": "0",
        "width": "auto",
        "height": "3px",
        "borderRadius": "0",
        "backgroundColor": "light-dark(var(--color-accent), var(--color-highlight))",
        "transition": "opacity var(--duration-medium) var(--ease-standard)"
      }
    },
    "tab-menu-item": {
      "base": {
        "borderRadius": "0",
        "color": "var(--color-text-secondary)",
        "transition": "background-color var(--duration-medium) var(--ease-standard), color var(--duration-medium) var(--ease-standard)",
        ":hover": {
          "backgroundColor": "light-dark(var(--color-accent-muted), rgba(255,255,255,.08))",
          "color": "var(--color-text-primary)"
        }
      }
    },
    "radio-indicator": {
      "base": {
        "width": "22px",
        "height": "22px",
        "borderWidth": "1.5px",
        "borderStyle": "solid",
        "borderColor": "var(--color-border-emphasized)",
        "backgroundColor": "light-dark(var(--color-background-surface), rgba(255,255,255,.06))",
        "transition": "border-color var(--duration-medium) var(--ease-standard), background-color var(--duration-medium) var(--ease-standard)"
      },
      "checked": {
        "borderColor": "light-dark(var(--color-accent), var(--color-highlight))"
      }
    },
    "radio-indicator-dot": {
      "base": {
        "width": "8px",
        "height": "8px",
        "backgroundColor": "light-dark(var(--color-accent), var(--color-highlight))"
      }
    },
    "checkbox-indicator": {
      "base": {
        "width": "22px",
        "height": "22px",
        "borderRadius": "0",
        "borderWidth": "1.5px",
        "borderStyle": "solid",
        "borderColor": "var(--color-border-emphasized)",
        "backgroundColor": "light-dark(var(--color-background-surface), rgba(255,255,255,.06))",
        "position": "relative",
        "transition": "border-color var(--duration-medium) var(--ease-standard), background-color var(--duration-medium) var(--ease-standard)"
      },
      "checked": {
        "backgroundColor": "light-dark(var(--color-accent), var(--color-highlight))",
        "borderColor": "light-dark(var(--color-accent), var(--color-highlight))",
        "color": "light-dark(#FFFFFF, var(--color-night))"
      }
    },
    "checkbox-indicator-check": {
      "base": {
        "width": "14px",
        "height": "14px"
      }
    },
    "checkbox-indicator-dash": {
      "base": {
        "display": "none"
      }
    },
    "switch": {
      "base": {
        "width": "46px",
        "height": "26px",
        "borderRadius": "9999px",
        "backgroundColor": "light-dark(var(--color-border-emphasized), rgba(255,255,255,.2))",
        "transition": "background-color var(--duration-medium) var(--ease-standard)"
      },
      "checked": {
        "backgroundColor": "light-dark(var(--color-accent), var(--color-highlight))"
      }
    },
    "switch-thumb": {
      "base": {
        "width": "20px",
        "height": "20px",
        "backgroundColor": "#FFFFFF",
        "boxShadow": "0 1px 3px rgba(0,0,0,.25)",
        "transition": "transform var(--duration-medium) var(--ease-standard)"
      },
      "checked": {
        "transform": "translateX(20px)"
      }
    },
    "slider-track": {
      "base": {
        "height": "6px",
        "borderRadius": "3px",
        "backgroundImage": "linear-gradient(90deg, color-mix(in srgb, var(--color-highlight) 26%, light-dark(#FFFFFF, var(--color-night))), color-mix(in srgb, var(--color-accent) 26%, light-dark(#FFFFFF, var(--color-night))))"
      }
    },
    "slider-thumb": {
      "base": {
        "width": "16px",
        "height": "16px",
        "backgroundColor": "var(--color-accent)",
        "boxShadow": "0 1px 4px rgba(0,0,0,.3)",
        "borderWidth": "0",
        "transition": "background-color var(--duration-medium) var(--ease-standard), box-shadow var(--duration-medium) var(--ease-standard)",
        ":hover": {
          "backgroundColor": "var(--color-accent-deep)"
        }
      }
    },
    "file-input": {
      "mode:dropzone": {
        "borderWidth": "1.5px",
        "borderStyle": "dashed",
        "borderColor": "var(--color-border-emphasized)",
        "backgroundColor": "light-dark(var(--color-background-surface), rgba(255,255,255,.05))",
        "borderRadius": "0",
        "padding": "18px 20px",
        "transition": "border-color var(--duration-medium) var(--ease-standard), background-color var(--duration-medium) var(--ease-standard)",
        ":hover": {
          "borderColor": "var(--color-accent)",
          "backgroundColor": "var(--color-accent-muted)"
        }
      }
    },
    "input-clear-button": {
      "base": {
        "borderWidth": "0",
        "backgroundColor": "transparent",
        "boxShadow": "none",
        "color": "var(--color-icon-secondary)",
        "padding": "0",
        "minWidth": "0",
        "width": "24px",
        "height": "24px",
        "transition": "color var(--duration-medium) var(--ease-standard)",
        ":hover": {
          "backgroundColor": "transparent",
          "color": "var(--color-text-accent)"
        }
      }
    },
    "input-clear-icon": {
      "base": {
        "width": "16px",
        "height": "16px"
      }
    },
    "badge": {
      "base": {
        "borderRadius": "0"
      },
      "variant:chip": {
        "height": "28px",
        "padding": "0 11px",
        "lineHeight": "1",
        "borderWidth": "var(--border-width)",
        "borderStyle": "solid",
        "borderColor": "var(--color-border-emphasized)",
        "backgroundColor": "var(--color-background-surface)",
        "color": "var(--color-text-secondary)",
        "fontSize": "11px",
        "fontWeight": "var(--font-weight-semibold)",
        "letterSpacing": "0.03em"
      },
      "variant:chip-high": {
        "height": "28px",
        "padding": "0 11px",
        "lineHeight": "1",
        "borderWidth": "0",
        "backgroundColor": "color-mix(in srgb, var(--color-highlight) 18%, transparent)",
        "color": "light-dark(var(--color-highlight-deep), var(--color-highlight))",
        "fontSize": "11px",
        "fontWeight": "var(--font-weight-semibold)",
        "letterSpacing": "0.03em"
      },
      "variant:chip-accent": {
        "height": "28px",
        "padding": "0 11px",
        "lineHeight": "1",
        "borderWidth": "0",
        "backgroundColor": "light-dark(var(--color-accent-muted), rgba(255,255,255,.1))",
        "color": "light-dark(var(--color-text-accent), var(--color-highlight))",
        "fontSize": "11px",
        "fontWeight": "var(--font-weight-semibold)",
        "letterSpacing": "0.03em"
      },
      "variant:chip-cat": {
        "height": "28px",
        "padding": "0 13px",
        "lineHeight": "1",
        "borderWidth": "0",
        "backgroundColor": "var(--color-accent)",
        "color": "var(--color-on-accent)",
        "fontSize": "11px",
        "fontWeight": "var(--font-weight-medium)",
        "letterSpacing": "0.16em",
        "textTransform": "uppercase"
      },
      "variant:chip-danger": {
        "height": "28px",
        "padding": "0 11px",
        "lineHeight": "1",
        "borderWidth": "0",
        "backgroundColor": "var(--color-error-muted)",
        "color": "var(--color-error)",
        "fontSize": "11px",
        "fontWeight": "var(--font-weight-semibold)",
        "letterSpacing": "0.03em"
      }
    },
    "card": {
      "base": {
        "borderRadius": "0"
      }
    },
    "dialog": {
      "base": {
        "borderRadius": "0",
        "backgroundColor": "var(--color-background-surface)",
        "boxShadow": "0 30px 80px -24px rgba(7,9,26,.6)",
        "::backdrop": {
          "backgroundImage": "radial-gradient(120% 120% at 50% -10%, color-mix(in srgb, var(--color-accent) 40%, transparent), transparent 66%)",
          "backdropFilter": "blur(5px)"
        }
      }
    }
  },
  __onDark: {
    "tokens": {
      "color-scheme": "dark",
      "--color-text-primary": "var(--color-on-dark)",
      "--color-icon-primary": "var(--color-on-dark)",
      "--color-accent": "var(--color-on-dark)"
    }
  },
  __onLight: {
    "tokens": {
      "color-scheme": "light",
      "--color-text-primary": "var(--color-on-light)",
      "--color-icon-primary": "var(--color-on-light)",
      "--color-accent": "var(--color-on-light)"
    }
  },

};
